### PR TITLE
use backticks everywhere

### PR DESCRIPTION
**Pull request by samjewell**
Just thinking this would be a good change to make- any thoughts for or against?

### CODE REVIEW

**Comment by samjewell** [comment]
@jackfranklin @maxmurdoch - how do you guys feel about this one?

**Comment by jackfranklin** [comment]
I personally wouldn't do this, but I would change it to:

- Use single quotes for strings
- Never concatenate strings with `+`, prefer template strings.

My reasoning:

- There's no need for template strings unless interpolating (there also is a tiny perf hit but that's not really a consideration).
- I think it's clearer to be able to see a template string and therefore know that something's being interpolated into it.

Thoughts?

**Comment by samjewell** [comment]
One more advantage of using backticks everywhere is that when you come to add some interpolation, there is less to change (you don't need to change the quotes). Also means less in the diff on github, so less distractions, although that could be argued as a reason not to do this.

**Comment by maxmurdoch** [comment]
My suggestion would be to only use template strings when you're using a feature they offer above regular strings(multiple lines, interpolation, tagging, or obtaining the raw string). That way its semantics are precise.

**Comment by jackfranklin** [comment]
+1 with @maxmurdoch , he managed to say what I wanted to in a lot less words

**Comment by maxmurdoch** [comment]
:kiss:

**Comment by samjewell** [comment]
Cool, cheers for the comments guys :-)

**Pull request closed without merging**
