### PR TITLE
tests don't support es6 - yet

### PR DESCRIPTION
**Pull request by samjewell**
:-(

This made me so sad

screen shot 2015-02-25 at 18 56 25

### CODE REVIEW

**Comment by samjewell** [comment]
@maxmurdoch @jackfranklin are you happy with this?

**Comment by samjewell** [comment]
LMK if you think this would be better as a paragraph rather than an `<h5>` - I'm guessing that would be better...?

screen shot 2015-02-25 at 19 08 25

**Comment by jackfranklin** [comment]
Ah yeah I forgot the E2E tests don't run through Traceur.

TBH I'm not sure if this is worth having in the guide though, feels very specific. Or we should make our E2E tests be compiled along with the rest of the app.

@harrison @maxmurdoch what do you think here?

**Comment by harrison** [comment]
yeah could maybe use the bable require hook in the protractor conf file, should then transpile all subsequently required files

`require("babel/register");`

**Comment by samjewell** [comment]
I'd really like for our repo and the styleguide to be consistent, and for it to be a place where we can turn to when we're not sure what style we should be using. Otherwise what's the point? That way we can point new hires or people from other teams at the styleguide, and they won't fall foul of weird idiosyncracies in our codebase.

**Comment by jackfranklin** [comment]
Or we could switch our tests to IO.js? ;)

**Comment by samjewell** [comment]
@maxmurdoch @jackfranklin Doesn't this:
```
// good
it('does a thing', () => {
});
```
contradict "Use function expressions when the function body is a block"

I wonder if what we really mean is:
```
Only ever use named functions or arrow functions, never anonymous functions
```
That would result in us using arrow functions widely in our tests, where currently they are anonymous - achieving `keeps tests cleaner and easier to pick out the actual assertions`

**Comment by jackfranklin** [comment]
@samjewell happy with this but wouldn't put it as a heading - just put it as regular text. Also 'node' => 'Node.js'.

WRT your Q, tests are the exception to the rule here. I should make that clearer.

**Comment by samjewell** [comment]
Cool, thanks @jackfranklin, will get that updated and merged in now. Feels like this'll be a good stopgap just while we're missing ES6 compilation from the e2e tests :smile:

**Comment by samjewell** [comment]
Also thanks for clarifying with the other thing- multiline arrow funcs in tests - just good to know what's going on :boat: :tophat:

**Comment by jackfranklin** [comment]
Nice!

**Pull request merged**
